### PR TITLE
Port charts to newest version of react-google-charts

### PR DESCRIPTION
**Pull request by divslingerx**
Port charts to the newest version of react-google-charts in reference to #80

### CODE REVIEW

**Comment by zrrrzzt** [comment]
Thank you for the PR @Toreilly317 

I see the `standard` parts of the tests are failing. Would you be so kind to do a `npm run standard-fix` and update the PR?

**Comment by divslingerx** [comment]
sorry about that! will update shortly

**Comment by divslingerx** [comment]
anything I can do to help close this?

**Comment by maccyber** [comment]
Thanks for asking. Sorry for the late follow-up. The commit looks good.

It's a issue when you resize the window, though.

resize

The chart does not resize

**Comment by divslingerx** [comment]
Sorry just seeing this. I'll work on a fix

**Comment by maccyber** [comment]
Amazing @Toreilly317. Thanks! Will merge after work :-)

**Pull request merged**
